### ISSUE TITLE
Create User stories

### ISSUE THREAD

**Issue by jijip41** [fac22/mixlist#6]

**Comment by cem-al** [comment]
As a user I want to be able to sign-up for an account

**Comment by jijip41** [comment]
As a user I want to be able to follow my friends

**Comment by cem-al** [comment]
As a user I want to be able to login and see my profile

**Comment by cem-al** [comment]
As a user I want to be able to add albums to my mixlist collection

**Comment by jijip41** [comment]
As a user I want to be able to see what my friends recently listened

**Comment by cem-al** [comment]
As a user I want to be able to logout

**Comment by jijip41** [comment]
As a user I want to like the music I would like to listen later

**Comment by cem-al** [comment]
As a user I want to be able to browse the website on my phone and desktop computer

**Comment by cem-al** [comment]
As a user I want to be able to leave reviews for albums

**Comment by jijip41** [comment]
As a user I want to be able to rate music

**Comment by cem-al** [comment]
As a user I want to be able to share music with my friends via whatsapp

**Comment by MJOW1999** [comment]
As a user I want to have a list of favourite albums

**Comment by jijip41** [comment]
As a user I want to be able to search some music

**Comment by jijip41** [comment]
As a user I want to be able to use the app on my mobile, and desktop

**Comment by MJOW1999** [comment]
As a user I want to be recommended new music

**Comment by cem-al** [comment]
- [ ]
